title: ue.tknupimmug
description: Zwischen Angst und Mut liegt nur ein Herzschlag
author: Patrick Walter
logo: /static/img/avatar.png
github: https://github.com/gummipunkt
about: netzpolitiker, linker, kreistagsmitglied mainz-bingen, antifaschist.

baseurl: ""
url: "https://gummipunkt.eu"

disqus_shortname: gummipunkt
google_analytics:

share:
  twitter_username: \#
  fb_appid:


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
